# Generated by Django 4.2.2 on 2023-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='no_de_control',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
