# Generated by Django 4.2.2 on 2023-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproyecto', '0002_alter_alumnos_no_de_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='carrera',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
